name: build and push on docker hub
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag001
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5.8
      with:
        image: komal0094/docker-test
        
        tags: ${{steps.tag001.outputs.tag}}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
