name: build and push on docker hub
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: komal0094/docker-test
        tag: v2.0
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
